mrp/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('timepiece.urls')),
    path('', RedirectView.as_view(url='/time/')),
    path('mrp/', include('mrp_system.urls')),


    #authentication views
    url(r'^accounts/login/$', auth_views.LoginView.as_view(),
        name='auth_login'),
    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(),
        name='auth_logout'),
    url(r'^accounts/password-change/$',
        auth_views.PasswordChangeView.as_view(),
        name='change_password'),
    url(r'^accounts/password-change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),
    url(r'^accounts/password-reset/$',
        auth_views.PasswordResetView.as_view(),
        name='reset_password'),
    url(r'^accounts/password-reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^accounts/reset/done/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),

]

from django.conf import settings
from django.conf.urls.static import static

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

timepiece/entries/urls.py
from django.conf.urls import url

from timepiece.entries import views

urlpatterns = [
    url(r'^time/$',
        views.Dashboard.as_view(),
        name='dashboard'),

    # Active entry
    url(r'^entry/clock_in/$',
        views.clock_in,
        name='clock_in'),
    url(r'^entry/clock_out/$',
        views.clock_out,
        name='clock_out'),


    # Entries
    url(r'^entry/$',
        views.create_edit_entry,
        name='create_entry'),
    url(r'^time/(?P<entry_id>\d+)/edit/$',
        views.create_edit_entry,
        name='edit_entry'),
    url(r'^time/(?P<entry_id>\d+)/delete/$',
        views.delete_entry,
        name='delete_entry'),

]

timepiece/manager/urls.py
from django.conf.urls import url

from timepiece.manager import views


urlpatterns = [
   

    # Users
    url(r'^user/settings/$',
        views.EditSettings.as_view(),
        name='edit_settings'),
    url(r'^user/$',
        views.ListUsers.as_view(),
        name='list_users'),
    url(r'^user/create/$',
        views.CreateUser,
        name='create_user'),
    url(r'^user/(?P<user_id>\d+)/$',
        views.ViewUser.as_view(),
        name='view_user'),
    url(r'^user/(?P<user_id>\d+)/edit/$',
        views.EditUser.as_view(),
        name='edit_user'),
    url(r'^user/(?P<user_id>\d+)/delete/$',
        views.DeleteUser.as_view(),
        name='delete_user'),

    url(r'^weektimesheetcsv/(?P<date>\d{4}-\d{2}-\d{2})/$',
        views.week_timesheet,
        name='timesheet_csv'),
    url(r'^weektimesheet/$',
        views.WeekTimesheet.as_view(),
        name='week_timesheet'),
    

    # User timesheets
    url(r'^user/(?P<user_id>\d+)/timesheet/$',
        views.view_user_timesheet,
        name='view_user_timesheet'),
    

    # Projects
    url(r'^project/$',
        views.ListProjects.as_view(),
        name='list_projects'),
    url(r'^project/create/$',
        views.CreateProject,
        name='create_project'),
    url(r'^project/(?P<project_id>\d+)/$',
        views.ViewProject.as_view(),
        name='view_project'),
    url(r'^project/(?P<project_id>\d+)/edit/$',
        views.EditProject.as_view(),
        name='edit_project'),
    url(r'^project/(?P<project_id>\d+)/delete/$',
        views.DeleteProject.as_view(),
        name='delete_project'),

     # Project timesheets
    url(r'^project/(?P<project_id>\d+)/timesheet/$',
        views.ProjectTimesheet.as_view(),
        name='view_project_timesheet'),

      # User-project relationships
    url(r'^relationship/create/$',
        views.CreateRelationship.as_view(),
        name='create_relationship'),
    url(r'^relationship/delete/$',
        views.DeleteRelationship.as_view(),
        name='delete_relationship'),
    
    ]     

timepiece/urls.py
from django.conf.urls import include, url
from django.urls import reverse_lazy
from django.views.generic import RedirectView
from django.views.generic.base import TemplateView

urlpatterns = [
    # Redirect the base URL to the dashboard.
    url(r'^$', RedirectView.as_view(url=reverse_lazy('dashboard'), permanent=False)),

    url('', include('timepiece.manager.urls')),
    url('', include('timepiece.entries.urls')),
    
    url(r'^docs/usersguide/$', TemplateView.as_view(template_name='UsersGuide.txt'), name="usersguide"),
    url(r'^docs/usersguideadmin/$', TemplateView.as_view(template_name='UsersGuideAdmin.txt'), name="usersguideadmin"),
]

timepiece/entries/models.py
from collections import OrderedDict
from decimal import Decimal
import datetime

from dateutil.relativedelta import relativedelta

from django.contrib.auth.models import User
from django.core import validators
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import F, Q, Sum, Max, Min
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

from timepiece import utils
from timepiece.manager.models import Project


##@python_2_unicode_compatible
##class Activity(models.Model):
##    """
##    Represents different types of activity: debugging, developing,
##    brainstorming, QA, etc...
##    """
##    code = models.CharField(
##        max_length=5, unique=True,
##        help_text='Enter a short code to describe the type of activity that took place.')
##    name = models.CharField(
##        max_length=50,
##        help_text='Now enter a more meaningful name for the activity.')
##    billable = models.BooleanField(default=True)
##
##    def __str__(self):
##        return self.name
##
##    class Meta:
##        db_table = 'timepiece_activity'  # Using legacy table name
##        ordering = ('name',)
##        verbose_name_plural = 'activities'
##
##
##@python_2_unicode_compatible
##class ActivityGroup(models.Model):
##    """Activities that are allowed for a project"""
##    name = models.CharField(max_length=255, unique=True)
##    activities = models.ManyToManyField(Activity, related_name='activity_group')
##
##    class Meta:
##        db_table = 'timepiece_activitygroup'  # Using legacy table
##
##    def __str__(self):
##        return self.name
##
##
##@python_2_unicode_compatible
##class Location(models.Model):
##    name = models.CharField(max_length=255, unique=True, blank=True, null=True)
##    slug = models.CharField(max_length=255, unique=True, blank=True, null=True)
##
##    class Meta:
##        db_table = 'timepiece_location'  # Using legacy table name
##
##    def __str__(self):
##        return self.name
##
##
class EntryQuerySet(models.query.QuerySet):
    """QuerySet extension to provide filtering by billable status"""

    def date_trunc(self, key='month', extra_values=None):
        select = {
            "day": {"date": """DATE_TRUNC('day', end_time)"""},
            "week": {"date": """DATE_TRUNC('week', end_time)"""},
            "month": {"date": """DATE_TRUNC('month', end_time)"""},
            "year": {"date": """DATE_TRUNC('year', end_time)"""},
        }
        basic_values = (
            'user', 'date', 'user__first_name', 'user__last_name')
        
        extra_values = extra_values or ()
        qs = self.extra(select=select[key])
        qs = qs.values(*basic_values + extra_values)
        qs = qs.annotate(hours=Sum('hours')).order_by(
            'user__last_name',
            'user__first_name',
            'user__pk',
            'date')
        return qs

    def timespan(self, from_date, to_date=None, span=None, current=False):
        """
        Takes a beginning date a filters entries. An optional to_date can be
        specified, or a span, which is one of ('month', 'week', 'day').
        N.B. - If given a to_date, it does not include that date, only before.
        """
        if span and not to_date:
            diff = None
            if span == 'month':
                diff = relativedelta(months=1)
            elif span == 'week':
                diff = relativedelta(days=7)
            elif span == 'day':
                diff = relativedelta(days=1)
            if diff is not None:
                to_date = from_date + diff
        datesQ = Q(end_time__gte=from_date)
        datesQ &= Q(end_time__lt=to_date) if to_date else Q()
        datesQ |= Q(end_time__isnull=True) if current else Q()
        return self.filter(datesQ)


class EntryManager(models.Manager):

    def get_queryset(self):
        qs = EntryQuerySet(self.model)
        #qs = qs.select_related('project__name')

        # ensure our select_related are added.  Without this line later calls
        # to select_related will void ours (not sure why - probably a bug
        # in Django)
        # in other words: do not remove!
        str(qs.query)

        return qs

##        import django
##        if django.VERSION >= (1, 8):
##            # extra() is slowly but surely being deprecated.
##            # Newer Django versions have powerful F expressions to replace it.
##            # An entry is billable if both its project and activity are billable.
##            # We make use of a Django internal function to force the
##            # query to use the logical rather than bitwise conjunction operator.
##            project_billable = F('project__type__billable')
##            activity_billable = F('activity__billable')
##            logical_and = 'AND'  # bitwise would be '&'
##            billable = project_billable._combine(activity_billable, logical_and, False)
##            qs = qs.annotate(billable=billable)
##        else:
##            qs = qs.extra({
##                'billable': 'timepiece_activity.billable AND '
##                            'timepiece_attribute.billable',
##            })
       

    def date_trunc(self, key='month', extra_values=()):
        return self.get_queryset().date_trunc(key, extra_values)

    def timespan(self, from_date, to_date=None, span='month'):
        return self.get_queryset().timespan(from_date, to_date, span)


##class EntryWorkedManager(models.Manager):
##
##    def get_queryset(self):
##        qs = EntryQuerySet(self.model)
##        projects = utils.get_setting('TIMEPIECE_PAID_LEAVE_PROJECTS')
##        return qs.exclude(project__in=projects.values())
##

@python_2_unicode_compatible
class Entry(models.Model):
##    """
##    This class is where all of the time logs are taken care of
##    """
##    UNVERIFIED = 'unverified'
##    VERIFIED = 'verified'
##    APPROVED = 'approved'
##    INVOICED = 'invoiced'
##    NOT_INVOICED = 'not-invoiced'
##    STATUSES = OrderedDict((
##        (UNVERIFIED, 'Unverified'),
##        (VERIFIED, 'Verified'),
##        (APPROVED, 'Approved'),
##        (INVOICED, 'Invoiced'),
##        (NOT_INVOICED, 'Not Invoiced'),
##    ))

    user = models.ForeignKey(User, related_name='timepiece_entries', on_delete=models.CASCADE,)
    project = models.CharField(max_length=50, blank=False)
    project = models.ForeignKey('manager.Project', related_name='entries', on_delete=models.CASCADE,)
    #activity = models.ForeignKey(Activity, related_name='entries', blank=True, null=True, on_delete=models.CASCADE,)
    #location = models.ForeignKey(Location, blank=True, null=True, related_name='entries', on_delete=models.CASCADE,)
    #entry_group = models.ForeignKey(
     #   'contracts.EntryGroup', blank=True, null=True, related_name='entries',
      #  on_delete=models.SET_NULL)
##    status = models.CharField(
##        max_length=24, choices=STATUSES.items(), default=UNVERIFIED)

    start_time = models.DateTimeField()
    end_time = models.DateTimeField(blank=True, null=True, db_index=True)
    #seconds_paused = models.PositiveIntegerField(default=0)
    #pause_time = models.DateTimeField(blank=True, null=True)
    activities = models.CharField(max_length=50, blank=False)
    #comments = models.TextField(blank=True, null=True)
    date_updated = models.DateTimeField(auto_now=True)

    hours = models.DecimalField(max_digits=11, decimal_places=5, default=0)

    objects = EntryManager()
    #worked = EntryWorkedManager()
    no_join = models.Manager()

    class Meta:
        db_table = 'timepiece_entry'  # Using legacy table name
        ordering = ('-start_time',)
        verbose_name_plural = 'entries'
        permissions = (
            ('can_clock_in', 'Can use Pendulum to clock in'),
            ('can_clock_out', 'Can use Pendulum to clock out'),
        )

    def __str__(self):
        return '%s on %s' % (self.user, self.project)

    def check_overlap(self, entry_b, **kwargs):
        """Return True if the two entries overlap."""
        consider_pause = False #kwargs.get('pause', True)
        entry_a = self
        # if entries are open, consider them to be closed right now
        if not entry_a.end_time or not entry_b.end_time:
            return False
        # Check the two entries against each other
        start_inside = entry_a.start_time > entry_b.start_time \
            and entry_a.start_time < entry_b.end_time
        """end_inside = entry_a.end_time > entry_b.start_time \
            and entry_a.end_time < entry_b.end_time"""
        a_is_inside = entry_a.start_time > entry_b.start_time \
            and entry_a.end_time < entry_b.end_time
        b_is_inside = entry_a.start_time < entry_b.start_time \
            and entry_a.end_time > entry_b.end_time
        overlap = start_inside or """end_inside""" or a_is_inside or b_is_inside
        if not consider_pause:
            return overlap
        else:
            if overlap:
                max_end = max(entry_a.end_time, entry_b.end_time)
                min_start = min(entry_a.start_time, entry_b.start_time)
                diff = max_end - min_start
                diff = diff.seconds + diff.days * 86400
                total = entry_a.get_total_seconds() + entry_b.get_total_seconds() - 1
                if total >= diff:
                    return True
            return False

    def is_overlapping(self):
        if self.start_time and self.end_time:
            entries = self.user.timepiece_entries.filter(
                Q(end_time__range=(self.start_time, self.end_time)) |
                Q(start_time__range=(self.start_time, self.end_time)) |
                Q(start_time__lte=self.start_time, end_time__gte=self.end_time)
            )

            totals = entries.aggregate(max=Max('end_time'), min=Min('start_time'))

            totals['total'] = 0
            for entry in entries:

timepiece/models.py
from django.db import models

# Create your models here.

timepiece/utils/views.py
from django.utils.decorators import method_decorator


def cbv_decorator(function_decorator):
    """Allows a function-based decorator to be used on a CBV."""

    def class_decorator(View):
        View.dispatch = method_decorator(function_decorator)(View.dispatch)
        return View
    return class_decorator


def format_totals(entry_dict, key="sum"):
    for entry in entry_dict:
        if entry[key]:
            entry[key] = "{0:.2f}".format(entry[key])


class GetDataFormMixin(object):
    """Used with subclasses of FormMixin to use GET data from the request."""

    def get_form_data(self):
        return self.request.GET or None

    def get_form_kwargs(self):
        kwargs = super(GetDataFormMixin, self).get_form_kwargs()
        kwargs.update({
            'data': self.get_form_data(),
        })
        return kwargs

timepiece/views.py
from django.shortcuts import render

# Create your views here.

timepiece/templates/timepiece/entry/clock_in.html
{% extends 'timepiece/base.html' %}

{% load static %}
{% load timepiece_tags %}

{% block crumbs %}
    {{ block.super }}
    <li><span class="divider">/</span> <a href="{% url 'clock_in' %}">Clock In</a></li>
{% endblock crumbs %}

{% block title %}Clock In{% endblock title %}

{% block extrajs %}
    <script charset="utf-8" src="{% static "timepiece/js/prevent_double_click.js" %}"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            function newParameters(query) {
                query.project = $('#id_project').val();
            }
            $('#id_activity_0').djselectable('option', 'prepareQuery', newParameters);
        });
    </script>
    <script>
        $.ui.djselectable.prototype._comboButtonTemplate = function (input) {
            var icon = $("<i>").addClass("icon-chevron-down");
            // Remove current classes on the text input
            $(input).attr("class", "");
            // Wrap with input-append
            $(input).wrap('<div class="input-append" />');
            // Return button link with the chosen icon
            return $("<a>").append(icon).addClass("btn ");
        };
        $.ui.djselectable.prototype._removeButtonTemplate = function (item) {
            var icon = $("<i>").addClass("icon-remove-sign");
            // Return button link with the chosen icon
            return $("<a>").append(icon).addClass("btn pull-right");
        };
    </script>
{% endblock extrajs %}

{% block content %}
    <div class="container-fluid">
        <div class="span12">
            <h2>Clock Into Project</h2>

            <br style="clear: both;" />

            {% if active %}
                <div>
                    <button type="button" class="close" data-dismiss="alert">x</button>
                    <h4 class="alert-heading">Switching Projects</h4>
                    <p>You are currently clocked into {{active.activity.name }} for {{ active.project }} with {{ active.get_total_seconds|humanize_seconds }} time clocked. Switching to a new project below will clock out of this entry and start a new one. Please enter any notes about switching below.</p>
                </div>
            {% endif %}

            <form class="form-horizontal prevent-doubleclick" accept-charset="utf-8"
                    action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form-actions">
                    <input class="btn btn-primary" type="submit" name="submit" value="Clock In" />
                    <input class="btn cancel" type="button" value="Cancel" onclick="history.back()" />
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

timepiece/templates/timepiece/entry/clock_out.html
{% extends 'timepiece/base.html' %}

{% load static %}

{% block crumbs %}
    {{ block.super }}
    <li><span class="divider">/</span> <a href="{% url 'clock_out' %}">Clock Out</a></li>
{% endblock crumbs %}

{% block title %}Clock Out of {{ entry.project }}{% endblock title %}

{% block extrajs %}
    <script charset="utf-8" src="{% static "timepiece/js/prevent_double_click.js" %}"></script>
{% endblock extrajs %}

{% block content %}
    <div class="container-fluid">
        <div class="span12">
            <h2>Clock Out of {{ entry.project }}</h2>

            <br style="clear: both;" />

            <form class="form-horizontal prevent-doubleclick" accept-charset="utf-8"
                    action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form-actions">
                    <input class="btn btn-primary" type="submit" name="submit" value="Clock Out" />
                    <input class="btn" type="button" value="Cancel" onclick="history.back()" />
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

timepiece/templates/timepiece/entry/create_edit.html
{% extends 'timepiece/base.html' %}

{% block title %}{% if entry %}Update{% else %}Create{% endif %} Entry{% endblock title %}

{% block extrajs %}
    <script type="text/javascript">
        $(document).ready(function() {
            function newParameters(query) {
                query.project = $('#id_project').val();
            }
            $('#id_activity_0').djselectable('option', 'prepareQuery', newParameters);
        });
    </script>
    <script>
        $.ui.djselectable.prototype._comboButtonTemplate = function (input) {
            var icon = $("<i>").addClass("icon-chevron-down");
            // Remove current classes on the text input
            $(input).attr("class", "");
            // Wrap with input-append
            $(input).wrap('<div class="input-append" />');
            // Return button link with the chosen icon
            return $("<a>").append(icon).addClass("btn ");
        };
        $.ui.djselectable.prototype._removeButtonTemplate = function (item) {
            var icon = $("<i>").addClass("icon-remove-sign");
            // Return button link with the chosen icon
            return $("<a>").append(icon).addClass("btn pull-right");
        };
    </script>
{% endblock extrajs %}

{% block crumbs %}
    {{ block.super }}
    {% if entry %}
        <li><span class="divider">/</span> <a href="{% url 'edit_entry' entry.pk %}">Update Entry</a></li>
    {% else %}
        <li><span class="divider">/</span> <a href="{% url 'create_entry' %}">Create Entry</a></li>
    {% endif %}
{% endblock crumbs %}

{% block content %}
    <div class="row-fluid">
        <div class="span12">
            <h2>{% if entry %}Update{% else %}Create{% endif %} Entry</h2>

            <br style="clear: both;" />

            <form class="form-horizontal" action="" method="post" accept-charset="utf-8">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form-actions">
                    <input class="btn btn-primary" type='submit' name='submit' value='Save' />
                    <input class="btn" type='button' value='Cancel' onclick="history.back()" />
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

timepiece/templates/timepiece/entry/delete.html
{% extends 'timepiece/base.html' %}

{% block title %}Delete Entry{% endblock title %}

{% block crumbs %}
    {{ block.super }}
    <li><span class="divider">/</span> <a href="{% url 'delete_entry' entry.pk %}">Delete Entry</a></li>
{% endblock crumbs %}

{% block content %}
    <div class="container-fluid">
        <div class="span12">
            <h2>Delete Entry</h2>

            <br style="clear: both;" />

            <form class="form-horizontal" action="" method="post">
                {% csrf_token %}
                <h3>Are you sure you want to delete this entry?</h3>
                <input type="hidden" name="key" value="{{ entry.delete_key }}" />
                <div class="form-actions">
                    <input class="btn btn-primary" type="submit" value="Yes" />
                    <input class="btn" type="button" value="No" onclick="history.back()" />
                </div>
            </form>
        </div>
    </div>
{% endblock content %}