mrp/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('timepiece.urls')),
    path('', RedirectView.as_view(url='/time/')),
    path('mrp/', include('mrp_system.urls')),


    #authentication views
    url(r'^accounts/login/$', auth_views.LoginView.as_view(),
        name='auth_login'),
    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(),
        name='auth_logout'),
    url(r'^accounts/password-change/$',
        auth_views.PasswordChangeView.as_view(),
        name='change_password'),
    url(r'^accounts/password-change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),
    url(r'^accounts/password-reset/$',
        auth_views.PasswordResetView.as_view(),
        name='reset_password'),
    url(r'^accounts/password-reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^accounts/reset/done/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),

]

from django.conf import settings
from django.conf.urls.static import static

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

timepiece/entries/urls.py
from django.conf.urls import url

from timepiece.entries import views

urlpatterns = [
    url(r'^time/$',
        views.Dashboard.as_view(),
        name='dashboard'),

    # Active entry
    url(r'^entry/clock_in/$',
        views.clock_in,
        name='clock_in'),
    url(r'^entry/clock_out/$',
        views.clock_out,
        name='clock_out'),


    # Entries
    url(r'^entry/$',
        views.create_edit_entry,
        name='create_entry'),
    url(r'^time/(?P<entry_id>\d+)/edit/$',
        views.create_edit_entry,
        name='edit_entry'),
    url(r'^time/(?P<entry_id>\d+)/delete/$',
        views.delete_entry,
        name='delete_entry'),

]

timepiece/manager/urls.py
from django.conf.urls import url

from timepiece.manager import views


urlpatterns = [
   

    # Users
    url(r'^user/settings/$',
        views.EditSettings.as_view(),
        name='edit_settings'),
    url(r'^user/$',
        views.ListUsers.as_view(),
        name='list_users'),
    url(r'^user/create/$',
        views.CreateUser,
        name='create_user'),
    url(r'^user/(?P<user_id>\d+)/$',
        views.ViewUser.as_view(),
        name='view_user'),
    url(r'^user/(?P<user_id>\d+)/edit/$',
        views.EditUser.as_view(),
        name='edit_user'),
    url(r'^user/(?P<user_id>\d+)/delete/$',
        views.DeleteUser.as_view(),
        name='delete_user'),

    url(r'^weektimesheetcsv/(?P<date>\d{4}-\d{2}-\d{2})/$',
        views.week_timesheet,
        name='timesheet_csv'),
    url(r'^weektimesheet/$',
        views.WeekTimesheet.as_view(),
        name='week_timesheet'),
    

    # User timesheets
    url(r'^user/(?P<user_id>\d+)/timesheet/$',
        views.view_user_timesheet,
        name='view_user_timesheet'),
    

    # Projects
    url(r'^project/$',
        views.ListProjects.as_view(),
        name='list_projects'),
    url(r'^project/create/$',
        views.CreateProject,
        name='create_project'),
    url(r'^project/(?P<project_id>\d+)/$',
        views.ViewProject.as_view(),
        name='view_project'),
    url(r'^project/(?P<project_id>\d+)/edit/$',
        views.EditProject.as_view(),
        name='edit_project'),
    url(r'^project/(?P<project_id>\d+)/delete/$',
        views.DeleteProject.as_view(),
        name='delete_project'),

     # Project timesheets
    url(r'^project/(?P<project_id>\d+)/timesheet/$',
        views.ProjectTimesheet.as_view(),
        name='view_project_timesheet'),

      # User-project relationships
    url(r'^relationship/create/$',
        views.CreateRelationship.as_view(),
        name='create_relationship'),
    url(r'^relationship/delete/$',
        views.DeleteRelationship.as_view(),
        name='delete_relationship'),
    
    ]     

timepiece/urls.py
from django.conf.urls import include, url
from django.urls import reverse_lazy
from django.views.generic import RedirectView
from django.views.generic.base import TemplateView

urlpatterns = [
    # Redirect the base URL to the dashboard.
    url(r'^$', RedirectView.as_view(url=reverse_lazy('dashboard'), permanent=False)),

    url('', include('timepiece.manager.urls')),
    url('', include('timepiece.entries.urls')),
    
    url(r'^docs/usersguide/$', TemplateView.as_view(template_name='UsersGuide.txt'), name="usersguide"),
    url(r'^docs/usersguideadmin/$', TemplateView.as_view(template_name='UsersGuideAdmin.txt'), name="usersguideadmin"),
]

timepiece/manager/models.py
from collections import OrderedDict

from django.apps import apps
from django.contrib.auth.models import User
from django.urls import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.db.models.signals import post_save
from django.dispatch import receiver

from timepiece.utils import get_active_entry


# Add a utility method to the User class that will tell whether or not a
# particular user has any unclosed entries
_clocked_in = lambda user: bool(get_active_entry(user))
User.add_to_class('clocked_in', property(_clocked_in))


# Utility method to get user's name, falling back to username.
_get_name_or_username = lambda user: user.get_full_name() or user.username
User.add_to_class('get_name_or_username', _get_name_or_username)


_get_absolute_url = lambda user: reverse('view_user', args=(user.pk,))
User.add_to_class('get_absolute_url', _get_absolute_url)


@python_2_unicode_compatible
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #hours_per_week = models.DecimalField(
       # max_digits=8, decimal_places=2, default=40)
    ssn = models.CharField(max_length=4, blank=True, default = ' ')
    title = models.CharField(max_length=20, blank=True, default = ' ')

    class Meta:
        db_table = 'manager_profile'  # Using legacy table name.

    """def __unicode__(self):
        return self.user.username"""
    

##class TypeAttributeManager(models.Manager):
##    """Object manager for type attributes."""
##
##    def get_queryset(self):
##        qs = super(TypeAttributeManager, self).get_queryset()
##        return qs.filter(type=Attribute.PROJECT_TYPE)
##
##
##class StatusAttributeManager(models.Manager):
##    """Object manager for status attributes."""
##
##    def get_queryset(self):
##        qs = super(StatusAttributeManager, self).get_queryset()
##        return qs.filter(type=Attribute.PROJECT_STATUS)
##
##
##@python_2_unicode_compatible
##class Attribute(models.Model):
##    PROJECT_TYPE = 'project-type'
##    PROJECT_STATUS = 'project-status'
##    ATTRIBUTE_TYPES = OrderedDict((
##        (PROJECT_TYPE, 'Project Type'),
##        (PROJECT_STATUS, 'Project Status'),
##    ))
##    SORT_ORDER_CHOICES = [(x, x) for x in range(-20, 21)]
##
##    type = models.CharField(max_length=32, choices=ATTRIBUTE_TYPES.items())
##    label = models.CharField(max_length=255)
##    sort_order = models.SmallIntegerField(
##        null=True, blank=True, choices=SORT_ORDER_CHOICES)
##    enable_timetracking = models.BooleanField(
##        default=False,
##        help_text=('Enable time tracking functionality for projects '
##                   'with this type or status.'))
##    billable = models.BooleanField(default=False)
##
##    objects = models.Manager()
##    types = TypeAttributeManager()
##    statuses = StatusAttributeManager()
##
##    class Meta:
##        db_table = 'timepiece_attribute'  # Using legacy table name.
##        unique_together = ('type', 'label')
##        ordering = ('sort_order',)
##
##    def __str__(self):
##        return self.label
##
##
##@python_2_unicode_compatible
##class Business(models.Model):
##    name = models.CharField(max_length=255)
##    short_name = models.CharField(max_length=255, blank=True)
##    email = models.EmailField(blank=True)
##    description = models.TextField(blank=True)
##    notes = models.TextField(blank=True)
##    external_id = models.CharField(max_length=32, blank=True)
##
##    class Meta:
##        db_table = 'timepiece_business'  # Using legacy table name.
##        ordering = ('name',)
##        verbose_name_plural = 'Businesses'
##        permissions = (
##            ('view_business', 'Can view businesses'),
##        )
##
##    def __str__(self):
##        return self.get_display_name()
##
##    def get_absolute_url(self):
##        return reverse('view_business', args=(self.pk,))
##
##    def get_display_name(self):
##        return self.short_name or self.name
##
##
class TrackableProjectManager(models.Manager):

    def get_queryset(self):
        return super(TrackableProjectManager, self).get_queryset().filter(
            inactive=False,
            #status__enable_timetracking=True,
            #type__enable_timetracking=True,
        )


@python_2_unicode_compatible
class Project(models.Model):
    name = models.CharField(max_length=255)
    users = models.ManyToManyField(User, related_name='user_projects', through='ProjectRelationship')
    inactive = models.BooleanField(blank=False, default=False)
    #activity_group = models.ForeignKey(
     #   'entries.ActivityGroup', related_name='activity_group', null=True,
      #  blank=True, verbose_name='restrict activities to')
##    type = models.ForeignKey(
##        Attribute, limit_choices_to={'type': 'project-type'},
##        related_name='projects_with_type', null=True, blank=True, on_delete=models.CASCADE,)
##    status = models.ForeignKey(
##        Attribute, limit_choices_to={'type': 'project-status'},
##        related_name='projects_with_status', null=True, blank=True, on_delete=models.CASCADE,)
##    description = models.TextField(blank=True, null=True)

    objects = models.Manager()
    trackable = TrackableProjectManager()

    class Meta:
        db_table = 'timepiece_project'  # Using legacy table name.
        ordering = ('name',) #'status', 'type',)
        #permissions = ( )

    def __str__(self):
        return '{0}'.format(self.name)

##    @property
##    def billable(self):
##        return self.type.billable

    def get_absolute_url(self):
        return reverse('view_project', args=(self.pk,))

##    def get_active_contracts(self):
##        Returns all associated contracts which are not marked complete.
##        ProjectContract = apps.get_model('contracts', 'ProjectContract')
##        return self.contracts.exclude(status=ProjectContract.STATUS_COMPLETE)

    def get_display_name(self):
        return self.name

##@python_2_unicode_compatible
##class RelationshipType(models.Model):
##    name = models.CharField(max_length=255, unique=True)
##    slug = models.SlugField(max_length=255)
##
##    class Meta:
##        db_table = 'timepiece_relationshiptype'  # Using legacy table name.
##
##    def __str__(self):
##        return self.name


@python_2_unicode_compatible
class ProjectRelationship(models.Model):
    #types = models.ManyToManyField(
       # RelationshipType, blank=True, related_name='project_relationships')
    user = models.ForeignKey(User, related_name='project_relationships', on_delete=models.CASCADE,)
    project = models.ForeignKey(Project, related_name='project_relationships', on_delete=models.CASCADE,)

    class Meta:
        db_table = 'timepiece_projectrelationship'  # Using legacy table name.
        unique_together = ('user', 'project')

    def __str__(self):
        return "{project}'s relationship to {user}".format(
            project=self.project.name,
            user=self.user.get_name_or_username(),
        )

        
##@python_2_unicode_compatible
##class Item_Type(models.Model):
##    name = models.CharField(max_length=255)
##    tracker_url = models.CharField(
##        max_length=255, blank=True, null=False, default="")
##    description = models.TextField( blank=True )
##
##    count = models.PositiveIntegerField(
##        default=0)
##        
##    class Meta:
##        db_table = 'timepiece_item_type'  # Using legacy table name.
##        ordering = ('name', 'count',)
##        permissions = (
##            ('view_inventory', 'Can view item type'),
##        )
##
##    def __str__(self):
##        return '{0}'.format(self.name)
##        
##    def get_display_name(self):
##        return self.name
##        
##    def get_absolute_url(self):
##        return reverse('view_item_type', args=(self.pk,))
##

timepiece/models.py
from django.db import models

# Create your models here.

timepiece/forms.py
import datetime
from dateutil.relativedelta import relativedelta
import time

from django import forms
from django.contrib.auth.models import User

from timepiece.fields import UserModelChoiceField

from timepiece.entries.models import Entry


DATE_FORM_FORMAT = '%Y-%m-%d'
INPUT_FORMATS = [DATE_FORM_FORMAT]


class TimepieceSplitDateTimeWidget(forms.SplitDateTimeWidget):

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('date_format', DATE_FORM_FORMAT)
        super(TimepieceSplitDateTimeWidget, self).__init__(*args, **kwargs)


class TimepieceSplitDateTimeField(forms.SplitDateTimeField):
    widget = TimepieceSplitDateTimeWidget


class TimepieceDateInput(forms.DateInput):

    def __init__(self, *args, **kwargs):
        kwargs['format'] = kwargs.get('format', DATE_FORM_FORMAT)
        super(TimepieceDateInput, self).__init__(*args, **kwargs)


class DateForm(forms.Form):
    from_date = forms.DateField(
        label='From', required=False, input_formats=INPUT_FORMATS,
        widget=TimepieceDateInput())
    to_date = forms.DateField(
        label='To', required=False, input_formats=INPUT_FORMATS,
        widget=TimepieceDateInput())

    def clean(self):
        from_date = self.cleaned_data.get('from_date', None)
        to_date = self.cleaned_data.get('to_date', None)
        if from_date and to_date and from_date > to_date:
            raise forms.ValidationError('The ending date must exceed the '
                                        'beginning date.')
        return self.cleaned_data

    def save(self):
        from_date = self.cleaned_data.get('from_date', '')
        to_date = self.cleaned_data.get('to_date', '')
        to_date = to_date + relativedelta(days=1) if to_date else to_date
        return (from_date, to_date)


class YearMonthForm(forms.Form):
    MONTH_CHOICES = [(i, time.strftime('%b', time.strptime(str(i), '%m')))
                     for i in range(1, 13)]
    month = forms.ChoiceField(choices=MONTH_CHOICES, label='')
    year = forms.ChoiceField(label='')

    def __init__(self, *args, **kwargs):
        super(YearMonthForm, self).__init__(*args, **kwargs)
        now = datetime.datetime.now()
        this_year = now.year
        this_month = now.month
        try:
            first_entry = Entry.no_join.values('end_time')\
                                       .order_by('end_time')[0]
        except IndexError:
            first_year = this_year
        else:
            first_year = first_entry['end_time'].year
        years = [(year, year) for year in range(first_year, this_year + 1)]
        self.fields['year'].choices = years
        initial = kwargs.get('initial')
        if initial:
            this_year = initial.get('year', this_year)
            this_month = initial.get('month', this_month)
        self.fields['year'].initial = this_year
        self.fields['month'].initial = this_month

    def save(self):
        now = datetime.datetime.now()
        this_year = now.year
        this_month = now.month
        month = int(self.cleaned_data.get('month', this_month))
        year = int(self.cleaned_data.get('year', this_year))
        from_date = datetime.datetime(year, month, 1)
        to_date = from_date + relativedelta(months=1)

        return (from_date, to_date)


class UserYearMonthForm(YearMonthForm):
    user = UserModelChoiceField(label='', queryset=None, required=False)

    def __init__(self, *args, **kwargs):
        super(UserYearMonthForm, self).__init__(*args, **kwargs)
        queryset = User.objects.exclude(timepiece_entries=None)\
                               .order_by('first_name')
        self.fields['user'].queryset = queryset

    def save(self):
        from_date, to_date = super(UserYearMonthForm, self).save()
        return (from_date, to_date, self.cleaned_data.get('user', None))

timepiece/utils/views.py
from django.utils.decorators import method_decorator


def cbv_decorator(function_decorator):
    """Allows a function-based decorator to be used on a CBV."""

    def class_decorator(View):
        View.dispatch = method_decorator(function_decorator)(View.dispatch)
        return View
    return class_decorator


def format_totals(entry_dict, key="sum"):
    for entry in entry_dict:
        if entry[key]:
            entry[key] = "{0:.2f}".format(entry[key])


class GetDataFormMixin(object):
    """Used with subclasses of FormMixin to use GET data from the request."""

    def get_form_data(self):
        return self.request.GET or None

    def get_form_kwargs(self):
        kwargs = super(GetDataFormMixin, self).get_form_kwargs()
        kwargs.update({
            'data': self.get_form_data(),
        })
        return kwargs

timepiece/views.py
from django.shortcuts import render

# Create your views here.

timepiece/templates/timepiece/project/base.html
{% extends "timepiece/base.html" %}

{% block crumbs %}
    {{ block.super }}
    <li><span class="divider">/</span> <a href="{% url 'list_projects' %}">Projects</a></li>
{% endblock crumbs %}

timepiece/templates/timepiece/project/create_edit.html
{% extends "timepiece/project/base.html" %}


{% block crumbs %}
    {{ block.super }}
    <li>
        <span class="divider">/</span>
        {% if not object %}
            <a href="{% url 'create_project' %}">Create Project</a>
        {% else %}
            <a href="{% url 'edit_project' object.pk %}">Edit Project</a>
        {% endif %}
    </li>
{% endblock crumbs %}

{% block title %}{% if not object %}Create Project{% else %}Edit {{ object }}{% endif %}{% endblock title %}

{% block content %}
    <div class="container-fluid">
        <div class="span12">
            <h2>{% if not object %}Create Project{% if business %} for {{ business }}{% endif %}{% else %}Edit {{ object }}{% endif %}</h2>

            <br style="clear: both;" />

            <form id="create-edit-project" class="form-horizontal" action="" method="post" accept-charset="utf-8">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form-actions">
                    <input class="btn btn-primary" type='submit' name='submit' value='Save' />
                    <input class="btn" type='button' value='Cancel' onclick='history.go(-1)' />
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

timepiece/templates/timepiece/project/createproject.html
{% extends "timepiece/project/base.html" %}
{% load timepiece_tags %}

{% block title %} Create Project
{% endblock title %}

{% block content %}
    <div class="row-fluid">
        <div class="span12">
            <h2>Create Project</h2>
<form class="form-horizontal" action="" method="post" accept-charset="utf-8">
  {% csrf_token %}
  {{ user_form.as_p }}
  

  <div class="form-actions">
                    <input class="btn btn-primary" type="submit" value="Next" name="submit" />
                    <input class="btn" type="button" onclick="history.go(-1)" value="Cancel" />
  </div>
</form>
</div>
</div>
{% endblock content %}

timepiece/templates/timepiece/project/list.html
{% extends "timepiece/project/base.html" %}

{% block title %}Projects{% endblock title %}

{% block content %}
    <div class="container-fluid">
        <div class="span12">
            <h2>Projects</h2>
            <ul class="nav nav-pills">
            {% if perms.crm.add_project %}
                <li><a href='{% url 'create_project' %}'>Create Project</a></li>
            {% endif %}
            </ul>
        </div>
    </div>
<br>
    <div class="container-fluid">
        <div class="span12">

            <table class='table table-striped table-bordered table-condensed'>
                <thead>
                    <tr>
                        <th style="width: 60%">Name</th>
                        <th>Time Sheet</th>
			  <th>Edit</th>
			 <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% for project in object_list %}
                        <tr>
                            <td><a href="{% url 'view_project' project.id %}">{{ project.name }}</a></td>
                            <td><a href="{% url 'view_project_timesheet' project.id %}">Time Sheet</a></td>
<td><a href="{% url 'edit_project' project.id %}">Edit</a></td>
                           <td><a href="{% url 'delete_project' project.id %}">Delete</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
{% endblock content %}

timepiece/templates/timepiece/project/timesheet.html
{% extends 'timepiece/project/base.html' %}
{% load timepiece_tags %}

{% block title %}{{ project }} - Time Sheet for {{ from_date|date:'M Y' }}{% endblock title %}

{% block crumbs %}
    {{ block.super }}
    <li><span class="divider">/</span> <a href="{% url 'view_project' project.pk %}">{{ project }}</a></li>
    <li><span class="divider">/</span> <a href="">Time Sheet</a></li>
{% endblock crumbs %}

{% block content %}
    <div class="container-fluid">
        <div class="span12">
            <h2>{{ project }} - Time Sheet for {{ from_date|date:'M Y' }}</h2>
        </div>
    </div>

    <div class="container-fluid">
        <div class="span12">
            <form class="form-horizontal" method="get" action="" id="date-filter" accept-charset="utf-8">
                {{ year_month_form }}
                <input class="btn btn-primary btn-sm" type='submit' name='yearmonth' value="Update" id='yearmonth'/>
                
            </form>
        </div>
    </div>
<br>
    <div class="container-fluid">
        {% if user_entries %}
            <div class="span3">
<h5>User Summary</h5>
                <table class='table table-bordered table-striped'>
                    
                {% for entry in user_entries %}
                    <tr>
                        <td>{{ entry.user__first_name }} {{ entry.user__last_name }}</td>
                        <td>{{ entry.sum }}</td>
                    </tr>
                {% endfor %}
                </table>
            </div>
        {% endif %}
    </div>

<hr>
    <div class="container-fluid">
        <div class="span12">
            {% if entries %}
                <table class="table table-bordered table-striped">
                    <tr>
                        <th>Date</th>
                        <th>User</th>
                        <th>Time In</th>
                        <th>Time Out</th>
                        
                        <th>Hours</th>
                        <th>Activities</th>
                    </tr>
                    {% for entry in entries %}
                    <tr>
                        <td>{{ entry.start_time|date:"m/d/Y (D)" }}</td>
                        <td>{{ entry.user__first_name }} {{ entry.user__last_name }}</td>
                        
                        <td>{{ entry.start_time|time }}</td>
                        <td>{{ entry.end_time|time }}</td>

                        <td>{{ entry.hours }}</td>
                        <td>{{ entry.activities|truncatewords:12 }}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan='4'>Total:</th>
                        <td>{{ total|floatformat:2 }}</td>
                       <td></td>
                    </tr>
                </table>
            {% else %}
                <p>No entries exist for this time sheet.</p>
            {% endif %}
        </div>
    </div>
{% endblock content %}

timepiece/templates/timepiece/project/view.html
{% extends "timepiece/project/base.html" %}
{% load timepiece_tags %}

{% block title %}{{ object }}{% endblock title %}

{% block crumbs %}
    {{ block.super }}
    <li><span class="divider">/</span> <a href="">{{ object }}</a></li>
{% endblock crumbs %}

{% block content %}
    <div class="container-fluid">
        <div class="span12">
            <h2>{{ object }}</h2>

            <ul class="nav nav-pills">
                    <li style="width: 5%"><a href="{% url 'edit_project' object.id %}">Edit</a></li>
                    <li style="width: 7%"><a href="{% url 'delete_project' object.id %}">Delete</a></li>
                    <li><a href="{% url 'view_project_timesheet' object.id %}">View Time Sheet</a></li>
               

            </ul>
        </div>
    </div>
<hr>
    <div class="container-fluid">
        
        <div class="span4 offset2">
            {% url 'view_project' object.id as next_url %}
            <h5>Users</h5>
            <ul class="users">
                {% for user in object.users.all %}
                    <li>
                        {{ user.get_name_or_username }}
                        
                            {% with caption="Remove "|add:user.get_name_or_username|add:" from "|add:object.name %}
                                <a title="{{ caption }}" href="{% url 'delete_relationship' %}?project_id={{ object.id }}&user_id={{ user.id }}&next={{ next_url|add_parameters:request.GET|urlencode }}"><i alt="{{ caption }}" class="fas fa-trash-alt"></i></a>
                            {% endwith %}
                       
                    </li>
                {% endfor %}
            </ul>
            
                <form class="form-horizontal" action="{% url 'create_relationship' %}?project_id={{ object.id }}&next={{ next_url|add_parameters:request.GET|urlencode }}" method="post" accept-charset="utf-8">
                    {% csrf_token %}
                    {{ add_user_form.as_p }}
                    <input class="btn btn-primary btn-sm" type="submit" value="Add" />
                </form>
            
        </div>
    </div>
{% endblock content %}