mrp/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('timepiece.urls')),
    path('', RedirectView.as_view(url='/time/')),
    path('mrp/', include('mrp_system.urls')),


    #authentication views
    url(r'^accounts/login/$', auth_views.LoginView.as_view(),
        name='auth_login'),
    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(),
        name='auth_logout'),
    url(r'^accounts/password-change/$',
        auth_views.PasswordChangeView.as_view(),
        name='change_password'),
    url(r'^accounts/password-change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),
    url(r'^accounts/password-reset/$',
        auth_views.PasswordResetView.as_view(),
        name='reset_password'),
    url(r'^accounts/password-reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^accounts/reset/done/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),

]

from django.conf import settings
from django.conf.urls.static import static

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

timepiece/entries/urls.py
from django.conf.urls import url

from timepiece.entries import views

urlpatterns = [
    url(r'^time/$',
        views.Dashboard.as_view(),
        name='dashboard'),

    # Active entry
    url(r'^entry/clock_in/$',
        views.clock_in,
        name='clock_in'),
    url(r'^entry/clock_out/$',
        views.clock_out,
        name='clock_out'),


    # Entries
    url(r'^entry/$',
        views.create_edit_entry,
        name='create_entry'),
    url(r'^time/(?P<entry_id>\d+)/edit/$',
        views.create_edit_entry,
        name='edit_entry'),
    url(r'^time/(?P<entry_id>\d+)/delete/$',
        views.delete_entry,
        name='delete_entry'),

]

timepiece/manager/urls.py
from django.conf.urls import url

from timepiece.manager import views


urlpatterns = [
   

    # Users
    url(r'^user/settings/$',
        views.EditSettings.as_view(),
        name='edit_settings'),
    url(r'^user/$',
        views.ListUsers.as_view(),
        name='list_users'),
    url(r'^user/create/$',
        views.CreateUser,
        name='create_user'),
    url(r'^user/(?P<user_id>\d+)/$',
        views.ViewUser.as_view(),
        name='view_user'),
    url(r'^user/(?P<user_id>\d+)/edit/$',
        views.EditUser.as_view(),
        name='edit_user'),
    url(r'^user/(?P<user_id>\d+)/delete/$',
        views.DeleteUser.as_view(),
        name='delete_user'),

    url(r'^weektimesheetcsv/(?P<date>\d{4}-\d{2}-\d{2})/$',
        views.week_timesheet,
        name='timesheet_csv'),
    url(r'^weektimesheet/$',
        views.WeekTimesheet.as_view(),
        name='week_timesheet'),
    

    # User timesheets
    url(r'^user/(?P<user_id>\d+)/timesheet/$',
        views.view_user_timesheet,
        name='view_user_timesheet'),
    

    # Projects
    url(r'^project/$',
        views.ListProjects.as_view(),
        name='list_projects'),
    url(r'^project/create/$',
        views.CreateProject,
        name='create_project'),
    url(r'^project/(?P<project_id>\d+)/$',
        views.ViewProject.as_view(),
        name='view_project'),
    url(r'^project/(?P<project_id>\d+)/edit/$',
        views.EditProject.as_view(),
        name='edit_project'),
    url(r'^project/(?P<project_id>\d+)/delete/$',
        views.DeleteProject.as_view(),
        name='delete_project'),

     # Project timesheets
    url(r'^project/(?P<project_id>\d+)/timesheet/$',
        views.ProjectTimesheet.as_view(),
        name='view_project_timesheet'),

      # User-project relationships
    url(r'^relationship/create/$',
        views.CreateRelationship.as_view(),
        name='create_relationship'),
    url(r'^relationship/delete/$',
        views.DeleteRelationship.as_view(),
        name='delete_relationship'),
    
    ]     

timepiece/urls.py
from django.conf.urls import include, url
from django.urls import reverse_lazy
from django.views.generic import RedirectView
from django.views.generic.base import TemplateView

urlpatterns = [
    # Redirect the base URL to the dashboard.
    url(r'^$', RedirectView.as_view(url=reverse_lazy('dashboard'), permanent=False)),

    url('', include('timepiece.manager.urls')),
    url('', include('timepiece.entries.urls')),
    
    url(r'^docs/usersguide/$', TemplateView.as_view(template_name='UsersGuide.txt'), name="usersguide"),
    url(r'^docs/usersguideadmin/$', TemplateView.as_view(template_name='UsersGuideAdmin.txt'), name="usersguideadmin"),
]

timepiece/models.py
from django.db import models

# Create your models here.

timepiece/forms.py
import datetime
from dateutil.relativedelta import relativedelta
import time

from django import forms
from django.contrib.auth.models import User

from timepiece.fields import UserModelChoiceField

from timepiece.entries.models import Entry


DATE_FORM_FORMAT = '%Y-%m-%d'
INPUT_FORMATS = [DATE_FORM_FORMAT]


class TimepieceSplitDateTimeWidget(forms.SplitDateTimeWidget):

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('date_format', DATE_FORM_FORMAT)
        super(TimepieceSplitDateTimeWidget, self).__init__(*args, **kwargs)


class TimepieceSplitDateTimeField(forms.SplitDateTimeField):
    widget = TimepieceSplitDateTimeWidget


class TimepieceDateInput(forms.DateInput):

    def __init__(self, *args, **kwargs):
        kwargs['format'] = kwargs.get('format', DATE_FORM_FORMAT)
        super(TimepieceDateInput, self).__init__(*args, **kwargs)


class DateForm(forms.Form):
    from_date = forms.DateField(
        label='From', required=False, input_formats=INPUT_FORMATS,
        widget=TimepieceDateInput())
    to_date = forms.DateField(
        label='To', required=False, input_formats=INPUT_FORMATS,
        widget=TimepieceDateInput())

    def clean(self):
        from_date = self.cleaned_data.get('from_date', None)
        to_date = self.cleaned_data.get('to_date', None)
        if from_date and to_date and from_date > to_date:
            raise forms.ValidationError('The ending date must exceed the '
                                        'beginning date.')
        return self.cleaned_data

    def save(self):
        from_date = self.cleaned_data.get('from_date', '')
        to_date = self.cleaned_data.get('to_date', '')
        to_date = to_date + relativedelta(days=1) if to_date else to_date
        return (from_date, to_date)


class YearMonthForm(forms.Form):
    MONTH_CHOICES = [(i, time.strftime('%b', time.strptime(str(i), '%m')))
                     for i in range(1, 13)]
    month = forms.ChoiceField(choices=MONTH_CHOICES, label='')
    year = forms.ChoiceField(label='')

    def __init__(self, *args, **kwargs):
        super(YearMonthForm, self).__init__(*args, **kwargs)
        now = datetime.datetime.now()
        this_year = now.year
        this_month = now.month
        try:
            first_entry = Entry.no_join.values('end_time')\
                                       .order_by('end_time')[0]
        except IndexError:
            first_year = this_year
        else:
            first_year = first_entry['end_time'].year
        years = [(year, year) for year in range(first_year, this_year + 1)]
        self.fields['year'].choices = years
        initial = kwargs.get('initial')
        if initial:
            this_year = initial.get('year', this_year)
            this_month = initial.get('month', this_month)
        self.fields['year'].initial = this_year
        self.fields['month'].initial = this_month

    def save(self):
        now = datetime.datetime.now()
        this_year = now.year
        this_month = now.month
        month = int(self.cleaned_data.get('month', this_month))
        year = int(self.cleaned_data.get('year', this_year))
        from_date = datetime.datetime(year, month, 1)
        to_date = from_date + relativedelta(months=1)

        return (from_date, to_date)


class UserYearMonthForm(YearMonthForm):
    user = UserModelChoiceField(label='', queryset=None, required=False)

    def __init__(self, *args, **kwargs):
        super(UserYearMonthForm, self).__init__(*args, **kwargs)
        queryset = User.objects.exclude(timepiece_entries=None)\
                               .order_by('first_name')
        self.fields['user'].queryset = queryset

    def save(self):
        from_date, to_date = super(UserYearMonthForm, self).save()
        return (from_date, to_date, self.cleaned_data.get('user', None))

timepiece/manager/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

#from selectable import forms as selectable

#from timepiece.utils.search import SearchForm

from timepiece.manager.models import (
    Profile, Project, ProjectRelationship
    )
from timepiece.fields import UserModelMultipleChoiceField


class CreateEditProjectForm(forms.ModelForm):
    
    class Meta:
        model = Project
        fields = ('name', 'inactive') 


class CreateUserForm(UserChangeForm):

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('ssn', 'title')

##class EditProjectRelationshipForm(forms.ModelForm):
##
##    class Meta:
##        model = ProjectRelationship
##        fields = ('types',)
##
##    def __init__(self, *args, **kwargs):
##        super(EditProjectRelationshipForm, self).__init__(*args, **kwargs)
##        self.fields[].widget = forms.CheckboxSelectMultiple(
##            choices=self.fields['types'].choices)


class EditUserForm(UserChangeForm):
    password1 = forms.CharField(
        required=False, max_length=36, label='Password',
        widget=forms.PasswordInput(render_value=False))
    password2 = forms.CharField(
        required=False, max_length=36, label='Repeat Password',
        widget=forms.PasswordInput(render_value=False))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'is_active',
                  'is_staff', 'groups')

    def __init__(self, *args, **kwargs):
        super(EditUserForm, self).__init__(*args, **kwargs)
        self.fields['groups'].widget = forms.CheckboxSelectMultiple()
        self.fields['groups'].help_text = None

        # In 1.4 this field is created even if it is excluded in Meta.
        if 'password' in self.fields:
            del(self.fields['password'])

    def clean(self):
        super(EditUserForm, self).clean()
        password1 = self.cleaned_data.get('password1', None)
        password2 = self.cleaned_data.get('password2', None)
        if password1 and password1 != password2:
            raise forms.ValidationError('Passwords must match.')
        return self.cleaned_data

    def save(self, commit=True):
        instance = super(EditUserForm, self).save(commit=False)
        password1 = self.cleaned_data.get('password1', None)
        if password1:
            instance.set_password(password1)
        if commit:
            instance.save()
            self.save_m2m()
        return instance


class EditUserSettingsForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super(EditUserSettingsForm, self).__init__(*args, **kwargs)
        for name in self.fields:
            self.fields[name].required = True


##class ProjectSearchForm(SearchForm):
##    #status = forms.ChoiceField(required=False, choices=[], label='')
##
##    def __init__(self, *args, **kwargs):
##        super(ProjectSearchForm, self).__init__(*args, **kwargs)
##        #statuses = Attribute.statuses.all()
##        #choices = [('', 'Any Status')] + [(a.pk, a.label) for a in statuses]
##        #self.fields['status'].choices = choices
##
##class QuickSearchForm(forms.Form):
##    quick_search = selectable.AutoCompleteSelectField(QuickLookup, required=False)
##    quick_search.widget.attrs['placeholder'] = 'Search'
##
##    def clean_quick_search(self):
##        item = self.cleaned_data['quick_search']
##        if not item:
##            msg = 'No user, business, or project matches your query.'
##            raise forms.ValidationError(msg)
##        return item
##
##    def get_result(self):
##        return self.cleaned_data['quick_search'].get_absolute_url()
##
##
##class SelectProjectForm(forms.Form):
##    project = selectable.AutoCompleteSelectField(ProjectLookup, label='')
##    project.widget.attrs['placeholder'] = 'Add Project'
##
##    def get_project(self):
##        return self.cleaned_data['project'] if self.is_valid() else None



class SelectMultipleUserForm(forms.Form):
    user = UserModelMultipleChoiceField(label='', queryset=None, required=False)

    def __init__(self, *args, **kwargs):
        super(SelectMultipleUserForm, self).__init__(*args, **kwargs)
        queryset = User.objects.order_by('first_name')
        self.fields['user'].queryset = queryset

    def get_user(self):
        users = []
        user1 = self.cleaned_data['user'] if self.is_valid() else None
        for user in user1:
            users.append(user)
        return users
        

timepiece/utils/views.py
from django.utils.decorators import method_decorator


def cbv_decorator(function_decorator):
    """Allows a function-based decorator to be used on a CBV."""

    def class_decorator(View):
        View.dispatch = method_decorator(function_decorator)(View.dispatch)
        return View
    return class_decorator


def format_totals(entry_dict, key="sum"):
    for entry in entry_dict:
        if entry[key]:
            entry[key] = "{0:.2f}".format(entry[key])


class GetDataFormMixin(object):
    """Used with subclasses of FormMixin to use GET data from the request."""

    def get_form_data(self):
        return self.request.GET or None

    def get_form_kwargs(self):
        kwargs = super(GetDataFormMixin, self).get_form_kwargs()
        kwargs.update({
            'data': self.get_form_data(),
        })
        return kwargs

timepiece/views.py
from django.shortcuts import render

# Create your views here.

timepiece/templates/timepiece/base.html
<!doctype html>

{% load static %}
<html>
<head>
    <title>Timepiece: {% block title %}{% endblock title %}</title>
    <link rel="icon" type="image/png" href="{% static "images/icons/timepiece.png" %}">
<link href="https://fonts.googleapis.com/css?family=Bitter" rel="stylesheet">                 
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    
	{% block stylesheet %}{% endblock %}

    {% block javascript %}
    <script charset="utf-8" src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    {% comment %}
    .button() is in both bootstrap & jqueryui. Selectable depends on
    jqueryui's, and bootstrap's is not currently used, so we'll load
    jqueryui last so that it has precedence.
    {% endcomment %}
    <script charset="utf-8" src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
    <script charset="utf-8" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
    <script charset="utf-8" src="{% static "selectable/js/jquery.dj.selectable.js" %}"></script>
    {% endblock javascript %}
{% comment %}
    {% if perms.crm.view_business %}  {# FIXME: Permission doesn't exist #}
        {{ quick_search_form.media.js }}
        <script charset="utf-8" src="{% static "timepiece/js/quick_search.js" %}"></script>
    {% endif %}
{% endcomment %}
    <script charset="utf-8" src="{% static "timepiece/js/widgets.js" %}"></script>


    {% block css %}
        <link type="text/css" rel="stylesheet"
                href="//ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/smoothness/jquery-ui.css" />
    {% endblock css %}

    

    {% block extracss %}
    {% endblock extracss %}
</head>

<body id="{% block bodyid %}{% endblock bodyid %}">

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  
  <a class="navbar-brand" href="{% url 'dashboard' %}">Timepiece</a>

  
  <ul class="navbar-nav">
<li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        <i class="far fa-clock"></i>
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'clock_in' %}">Clock in</a>
            <a class="dropdown-item" href="{% url 'create_entry' %}">Add Entry</a>
      </div>
    </li> 
{% if user.is_staff %}
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        Management
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
            <a class="dropdown-item" href="{% url 'list_projects' %}">Projects</a>
            <a class="dropdown-item" href="{% url 'list_users' %}">Users</a>
      </div>
    </li>
{% endif %}
<li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        Help
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="{% static "UsersGuide.txt" %}">Users Guide</a>
{% if user.is_staff %}            
<a class="dropdown-item" href="{% static "UsersGuideAdmin.txt" %}">Users Guide Admin</a>
{% endif %}
      </div>
    </li>


</ul>
{% if user.is_authenticated %}
<ul class="navbar-nav ml-auto">

<li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
       {{ user.first_name }}
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        <a class="dropdown-item" href="{% url 'edit_settings' %}">Settings</a>
            <a class="dropdown-item" href="{% url 'change_password' %}">Change Password</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'auth_logout' %}">Log out</a>
      </div>
    </li>
  </ul>
{% else %}
<a href="{% url 'auth_login' %}" class="btn btn-outline-secondary">Log in</a>
{% endif %}
</nav>



    <div id="content" class="container-fluid">

        {% if user.is_authenticated %}
            {% block breadcrumb %}
                <ul class="breadcrumb">
                    {% block crumbs %}
                        <li><a href="{% url 'dashboard' %}">Home</a></li>
                    {% endblock crumbs %}
                </ul>
            {% endblock breadcrumb %}
        {% endif %}

        {% block content %}
        {% endblock content %}
    </div>

    {% block footer %}
        <footer class="footer">
            <div class="container-fluid">
            </div>
        </footer>
    {% endblock footer %}

    <script charset="utf-8" src="{% static "timepiece/js/sticky_table_header.js" %}"></script>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block extrajs %}
    {% endblock extrajs %}
</body>

</html>

timepiece/templates/timepiece/dashboard.html
{% extends "timepiece/base.html" %}

{% load static %}
{% load timepiece_tags %}


{% block title %}Dashboard{% endblock title %}

{% block bodyid %}dashboard{% endblock bodyid %}

{% block breadcrumb %}{% endblock breadcrumb %}

{% block extrajs %}
    
    <script charset="utf-8" src="{% static "timepiece/js/permanent_tabs.js" %}"></script>

    <script>
        // The largest number of hours worked or assigned on any project.
        var max_hours = {% get_max_hours %};
    </script>
    <script charset="utf-8" src="{% static "timepiece/js/dashboard.js" %}"></script>
    <script charset="utf-8" src="{% static "timepiece/js/prevent_double_click.js" %}"></script>
    <script>
    $(document).ready(function(){
        $('[data-toggle="popover"]').popover();
    });
    </script>
{% endblock extrajs %}

{% block content %}
    {% if perms.entries.can_clock_in %}
        <h3> Timesheet </h3>

        <div  class="container-fluid">
            <div class="row">

                <div class="btn-group-sm">
                    
                        
                        {% if active_entry %}
                            <a class="btn btn-primary" href="{% url 'clock_out' %}">Clock Out</a>
                            <a class="btn btn-primary" href="{% url 'edit_entry' active_entry.pk %}">Edit</a>
                        {% endif %}
			<a class="btn btn-primary" href="{% url 'clock_in' %}">
                            {% if active_entry %}Switch{% else %}Clock In{% endif %}
                        </a>
                    
                        <a class="btn btn-primary" href="{% url 'create_entry' %}" title="Add Entry">Add Entry</a>
                   </div>
                </div>
<div class="container-fluid">
                <div id="active-text">
		<p>
                    {% if active_entry %}
                        You have been clocked into
                        <strong> {{ active_entry.project }}</strong>
                        since {{ active_entry.start_time|time }}
                        {% ifnotequal active_entry.start_time.date today %}
                            {% if active_entry.start_time.date < week_start or active_entry.start_time.date > week_end %}
                                on {{ active_entry.start_time|date:'M j' }}
                            {% else %}
                                on {{ active_entry.start_time|date:"l" }}
                            {% endif %}
                        {% endifnotequal %}
                        ({{ active_entry.get_total_seconds|humanize_seconds }} time clocked{% if active_entry.seconds_paused or active_entry.is_paused %} and {{ active_entry.get_paused_seconds|humanize_seconds }} paused{% endif %}).
    

                    {% else %}
                        You are not currently clocked into a project.
                    {% endif %}
</p>
                </div>
            </div>
        
        
	<div>
            <form class="form-horizontal" method="post" action="" accept-charset="utf-8">

               {% csrf_token %} 
		{{ form.as_p }}
                <input class="btn btn-primary btn-sm" type='submit' name='submit' value="Save" />
                
            </form>
        </div>
<hr>
    
        <div>
<p>
            <ul class="nav nav-pills">
                <li style="width: 17%"> <a href="{% url 'dashboard' %}?week_start={{ prev_week|date:'Y-m-d' }}">&larr; Prev Week</a></li>
                <li style="width: 17%"><a href="{% url 'dashboard' %}?week_start={{ next_week|date:'Y-m-d' }}">Next Week &rarr;</a></li>
            </ul>
</p>
        </div>
 
        <div class="tab-content">
<h3>Hours for the Week of {{ week|date:'M j' }}</h3>
            <div>
                {% if week_entries %}
                    {% url 'dashboard' as next_url %}
                    {% regroup week_entries by start_time|date:'l, F j' as daily_entries %}
                    <table class="table table-bordered">
                        
                            <tr class="table-secondary">
                                <th style="width: 25%">Project</th>
                                <th style="width: 15%">From</th>
                                <th style="width: 15%">To</th>
                                <th style="width: 15%">Total Time</th>
                                <th style="width: 23%">Activities</th>
				  
                            </tr>
                        
                        <tbody>
                            {% for day in daily_entries %}
                                {% sum_hours day.list as daily_total %}
                                <tr class="table-secondary">
                                    <th colspan="3">{{ day.grouper }}</th>
                                    
                                    <th colspan="2">{{ daily_total|humanize_seconds:"{hours:02d}:{minutes:02d}:{seconds:02d}" }}</th>
                                    
                                </tr>
                                {% for entry in day.list %}
                                    <tr>
                                        <td>
                                            <p class="mb-0">
                                            {{ entry.project }} </p>
<small class="text-muted">
                                                <a href="{% url 'edit_entry' entry.id %}?next={{ next_url|add_parameters:request.GET|urlencode }}">Edit</a>
                                                <a href="{% url 'delete_entry' entry.id %}?next={{ next_url|add_parameters:request.GET|urlencode }}">Delete</a>
                                        </td>
                                        
                                        <td class="align-middle">{{ entry.start_time|time }}</td>
                                        <td class="align-middle">
                                            {% if entry.end_time %}
                                                {{ entry.end_time|time }}
                                            {% else %}
                                                current
                                            {% endif %}
                                        </td>
                                        <td class="align-middle">{{ entry.get_total_seconds|humanize_seconds:"{hours:02d}:{minutes:02d}:{seconds:02d}" }}</td>
                                        <td class="align-middle">
                                                {{ entry.activities }}
                                        </td>
                                    </tr>
                                {% endfor %}
				    

                            {% endfor %}
  <tr class="totals">
                                <td colspan="3"><strong>Overall total for the period:</strong></td>
                                <td class="align-middle" colspan="2">{{ total_worked|humanize_hours:"{hours:02d}:{minutes:02d}:{seconds:02d}" }}</td>
                            </tr>
                        </tbody>
                    </table>
                {% else %}
                    <p>No entries exist for this week.</p>
                {% endif %}
            
                            <div>
                                <h3>Project Summary</h3>
{% if week_entries %}
                                <table class="table table-bordered">
                                    <thead>
                                        <tr class="table-secondary">
                                            <th>Project</th>
                                            <th>Hours</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for data in project_progress %}
                                            <tr>
                                                <td>{{ data.project}} </td>
                                                <td class="hours">{{ data.worked|humanize_hours:"{hours:02d}:{minutes:02d}:{seconds:02d}" }}</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
{% else %}
<p>No entries exist for this week.</p>
{% endif %}
                            </div>
		</div>		
        </div>
    {% endif %}
{% endblock content %}

timepiece/templates/timepiece/date_filters.html
<script>
    function update_dates(node) {
        var from_date = $("#id_from_date");
        var to_date = $("#id_to_date");
        from_date.val($(node).attr("from_date"));
        to_date.val($(node).attr("to_date"));
        $("#{{ form_id }}").submit();
    };
</script>

<ul class="date-filters">
    {% for filter_category, filter_list in filters.items %}
        <li>
            <ul>
                <li class="label">{{ filter_category }}</li>
                {% for label, from_date, to_date in filter_list %}
                    <li><a href="javascript:void(0);" class="date-filter" from_date="{{ from_date }}" to_date="{{ to_date }}" onclick="update_dates(this);">{{ label }}</a></li>
                {% endfor %}
            </ul>
        </li>
    {% endfor %}
</ul>

timepiece/templates/timepiece/delete_object.html
{% extends "timepiece/base.html" %}

{% block title %}
    Delete {{ object }}
{% endblock title %}

{% block content %}
    <div class="row-fluid">
        <div class="span12">
            {% if object.get_name_or_username %}
                <h3>Are you sure you want to delete {{ object.get_name_or_username }}?</h3>
            {% else %}
                <h3>Are you sure you want to delete {{ object }}?</h3>
            {% endif %}
            <form method="post" action="">
                {% csrf_token %}
                <input type="hidden" name="delete" value="delete" />
                <input type="submit" class="btn btn-danger" value="Delete" />
                <input type="button" class="btn" value="Do Not Delete" onclick="history.back(-1)" />
            </form>
        </div>
    </div>
{% endblock content %}

timepiece/templates/timepiece/profile.html
{% extends "timepiece/user/base.html" %}
{% load bootstrap_toolkit %}

{% block title %} Create User
{% endblock title %}

{% block content %}
    <div class="row-fluid">
        <div class="span12">
            <h2>Create User</h2>
<form class="form-horizontal" action="" method="post" accept-charset="utf-8">
  {% csrf_token %}
  {{ user_form.as_p }}
  {{ profile_form.as_p }}

  <div class="form-actions">
                    <input class="btn btn-primary" type="submit" value="Save" name="submit" />
                    <input class="btn" type="button" onclick="history.go(-1)" value="Cancel" />
  </div>
</form>
</div>
</div>
{% endblock content %}